
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: spotcode_development
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  database: spotcode_test

production:
  adapter: postgresql
  database: spotcode_production
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  role: postgres